require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/receden_medications", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # RecedenMedication. As you add validations to RecedenMedication, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RecedenMedication.create! valid_attributes
      get receden_medications_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      receden_medication = RecedenMedication.create! valid_attributes
      get receden_medication_url(receden_medication)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_receden_medication_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      receden_medication = RecedenMedication.create! valid_attributes
      get edit_receden_medication_url(receden_medication)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RecedenMedication" do
        expect {
          post receden_medications_url, params: { receden_medication: valid_attributes }
        }.to change(RecedenMedication, :count).by(1)
      end

      it "redirects to the created receden_medication" do
        post receden_medications_url, params: { receden_medication: valid_attributes }
        expect(response).to redirect_to(receden_medication_url(RecedenMedication.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RecedenMedication" do
        expect {
          post receden_medications_url, params: { receden_medication: invalid_attributes }
        }.to change(RecedenMedication, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post receden_medications_url, params: { receden_medication: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested receden_medication" do
        receden_medication = RecedenMedication.create! valid_attributes
        patch receden_medication_url(receden_medication), params: { receden_medication: new_attributes }
        receden_medication.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the receden_medication" do
        receden_medication = RecedenMedication.create! valid_attributes
        patch receden_medication_url(receden_medication), params: { receden_medication: new_attributes }
        receden_medication.reload
        expect(response).to redirect_to(receden_medication_url(receden_medication))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        receden_medication = RecedenMedication.create! valid_attributes
        patch receden_medication_url(receden_medication), params: { receden_medication: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested receden_medication" do
      receden_medication = RecedenMedication.create! valid_attributes
      expect {
        delete receden_medication_url(receden_medication)
      }.to change(RecedenMedication, :count).by(-1)
    end

    it "redirects to the receden_medications list" do
      receden_medication = RecedenMedication.create! valid_attributes
      delete receden_medication_url(receden_medication)
      expect(response).to redirect_to(receden_medications_url)
    end
  end
end
