require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/receden_diseases' do
  # This should return the minimal set of attributes required to create a valid
  # RecedenDisease. As you add validations to RecedenDisease, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      RecedenDisease.create! valid_attributes
      get receden_diseases_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      receden_disease = RecedenDisease.create! valid_attributes
      get receden_disease_url(receden_disease)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_receden_disease_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      receden_disease = RecedenDisease.create! valid_attributes
      get edit_receden_disease_url(receden_disease)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new RecedenDisease' do
        expect do
          post receden_diseases_url, params: { receden_disease: valid_attributes }
        end.to change(RecedenDisease, :count).by(1)
      end

      it 'redirects to the created receden_disease' do
        post receden_diseases_url, params: { receden_disease: valid_attributes }
        expect(response).to redirect_to(receden_disease_url(RecedenDisease.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new RecedenDisease' do
        expect do
          post receden_diseases_url, params: { receden_disease: invalid_attributes }
        end.not_to change(RecedenDisease, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post receden_diseases_url, params: { receden_disease: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested receden_disease' do
        receden_disease = RecedenDisease.create! valid_attributes
        patch receden_disease_url(receden_disease), params: { receden_disease: new_attributes }
        receden_disease.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the receden_disease' do
        receden_disease = RecedenDisease.create! valid_attributes
        patch receden_disease_url(receden_disease), params: { receden_disease: new_attributes }
        receden_disease.reload
        expect(response).to redirect_to(receden_disease_url(receden_disease))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        receden_disease = RecedenDisease.create! valid_attributes
        patch receden_disease_url(receden_disease), params: { receden_disease: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested receden_disease' do
      receden_disease = RecedenDisease.create! valid_attributes
      expect do
        delete receden_disease_url(receden_disease)
      end.to change(RecedenDisease, :count).by(-1)
    end

    it 'redirects to the receden_diseases list' do
      receden_disease = RecedenDisease.create! valid_attributes
      delete receden_disease_url(receden_disease)
      expect(response).to redirect_to(receden_diseases_url)
    end
  end
end
